# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-09 12:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=255, null=True)),
                ('part_of_speach', models.CharField(max_length=255, null=True)),
                ('frequency', models.IntegerField()),
                ('dispersion', models.FloatField(max_length=255, null=True)),
            ],
        ),
    ]
