- apt_repository: repo='deb http://apt.postgresql.org/pub/repos/apt/ trusty-pgdg main' state=present

- apt_key: url=https://www.postgresql.org/media/keys/ACCC4CF8.asc state=present

- apt: name=postgresql-client-9.4 state=present update_cache=yes

- name: create data directory for postgres
  file: path=/data/{{folder_name}}_postgresql state=directory mode=0700

- name: run postgres container
  docker:
    image: postgres:9.4
    ports:
      - 127.0.0.1:{{ postgres_port }}:5432
    name: "{{folder_name}}_postgres"
    env:
      POSTGRES_PASSWORD: "{{ postgres_password }}"
      POSTGRES_USER: "{{ postgres_user }}"
    restart_policy: always
    volumes:
      - "/data/{{folder_name}}_postgresql:/var/lib/postgresql/data"
    docker_api_version: 1.21
